### ISSUE TITLE
Mehrere Linien -> nur ein Gewinn

### ISSUE THREAD

**Issue by jlz915** [walterderhalter/dss#17]

**Comment by walterderhalter** [comment]
Anmerkung: 
Da ich selber schon keine Überblick mehr über meine Funktions Namen habe, habe ich in Commit 31d7570a PlayerInfo.Winning immer auf 0 gesetzt da ich dachte das die meine "Icon Reihen Such" Funktion sei.  Daher wurde jedesmal beim aufrufen das Winning zurück auf Null gesetzt. 
Es wurden alle Linien gewertet aber immer nur die letzte hat Gewinn gegeben.
