### ISSUE TITLE
Erhöhung der Ziffern im Punktespeicher

### ISSUE THREAD

**Issue by jlz915** [walterderhalter/dss#22]
Im Punktespeicher werden nur 4 Ziffern maximal angezeigt. 

Dementsprechend steht bei einem Wert von 10180 -> 1018.

Vorschlag: Erhöhung auf 6 oder sogar 7 Stellen.

(Edit)
Das Problem ist das Zahlen zu groß für die Textbox werden und abgeschnitten werden

**Comment by walterderhalter** [comment]
Mach Labels dran du Affe :D

**Comment by walterderhalter** [comment]
Problem gelöst! Es ist jetzt platz für ein Minus und 8 Stellen. Wenn dieses Limit erreicht wird verkleinert sich die Schriftart automatisch. Es kann jetzt also so viele Stellen geben bis man es nicht mehr lesen kann.
